### ISSUE TITLE
[BUG] spectator bug

### ISSUE THREAD

**Issue by Tmdoofking** [toppev/strikepractice-public#22]
**Describe the bug**
spectator can push minecart and disable crystal pacement

**To Reproduce**
1. spec a match
2. stand on obsidian / push minecart
3. player in fight can't place crystal on obsidian

**Expected behavior**
Able to place crystal
Disable minecart collision for spectator

**Checklist**
- [x] The issue occurs on latest version of StrikePractice.
- [x] The issue occurs without other plugins (or non-official addons).
- [x] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [x] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version 1.19.4 paper spigot

**Comment by toppev** [comment]
Unfortunately SP relies on (paper) spigot's ability to "allow players to place blocks even if an invisible player is there" (seems like you're already using paper so this may not be the case with crystals). You can enable `spectator-stay-away: true` in the config.yml and that will prevent players from getting too close, but won't fully prevent that.

**Comment by toppev** [comment]
There are now several solutions:

1.
```yaml
# Prevent players from flying to close to fighting players
spectator-stay-away: true
# Spectator check period in ticks
# lowering this will increase how often the above setting is checked
spectator-timer-period: 10
```

2. Use the actual spectator gamemode (config.yml)
3. Use different spigot (e.g., paper)
