### ISSUE TITLE
[BUG] spectator can pickup xporb bug

### ISSUE THREAD

**Issue by Tmdoofking** [toppev/strikepractice-public#24]
**Describe the bug**
spectator can pickup xporb

**To Reproduce**
1. spec match
2. pickup exp orb

**Expected behavior**
it won't get affect by spectator 

**Checklist**
- [ ] The issue occurs on latest version of StrikePractice.
- [ ] The issue occurs without other plugins (or non-official addons).
- [ ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version 1.19.4

**Comment by toppev** [comment]
I have plans to make spectators actually use the spectator gamemode in near future. Meanwhile I recommend these config.yml settings:
```yaml
# Prevent players from flying to close to fighting players
spectator-stay-away: false
# Spectator check period in ticks
# lowering this will increase how often the above setting is checked
spectator-timer-period: 10
```
